# Generated by Django 2.1.7 on 2019-03-17 23:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reseña', models.CharField(max_length=1000)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Banco')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reseña', models.CharField(max_length=1000)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazoMinDias', models.IntegerField()),
                ('tasa', models.FloatField()),
                ('montoMinimo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBancario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Banco')),
            ],
        ),
        migrations.AddField(
            model_name='cdt',
            name='productoBancario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ProductoBancario'),
        ),
        migrations.AddField(
            model_name='calificacionproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProductoBancario'),
        ),
    ]
