# Generated by Django 2.1.7 on 2019-03-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosRegistro',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('acepta', models.BooleanField()),
                ('telefono', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
