# Generated by Django 2.1.7 on 2019-03-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='numero_calificaciones',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banco',
            name='puntaje_total',
            field=models.FloatField(default=0),
        ),
    ]
