# Generated by Django 2.1.7 on 2019-03-21 00:00

from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):

    def create_slug(apps, schema_editor):
        Registro = apps.get_model('api', 'DatosRegistro')
        for r in Registro.objects.all():
            r.slug_name = slugify(r.email)
            r.save()

    dependencies = [
        ('api', '0002_datosregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosregistro',
            name='slug_name',
            field=models.SlugField(unique=True, null=True),
        ),
        migrations.RunPython(create_slug, reverse_code=migrations.RunPython.noop)
    ]

